const http = require('http');
const fs = require('fs');
const path = require('path');
const crypto = require('crypto');
const { createDatabase, hashPassword, verifyPassword } = require('./database');

const PORT = Number(process.env.PORT || 4173);
const ROOT = __dirname;
const db = createDatabase();
const rateWindow = new Map();
const allowedOrigins = new Set([process.env.FRONTEND_URL, 'http://127.0.0.1:5500', 'http://localhost:5500', `http://localhost:${PORT}`, `http://127.0.0.1:${PORT}`].filter(Boolean));

const medicineFacts = {
  paracetamol: { aliases: ['acetaminophen'], use: 'Pain and fever relief', safety: 'Follow the label or prescription. Do not combine multiple products containing paracetamol, and ask a pharmacist if you have liver disease or drink heavily.', sideEffects: 'Some people may develop nausea or a rash. Get urgent help for facial swelling, trouble breathing, or a severe skin reaction.', questions: 'Ask about other paracetamol-containing products, liver conditions, pregnancy, and the correct product strength.' },
  cetirizine: { aliases: ['cetirizine hcl'], use: 'Allergy symptom relief', safety: 'It may cause drowsiness in some people. Be careful with driving or alcohol until you know how it affects you.', sideEffects: 'Drowsiness, dry mouth, or tiredness can occur. Seek help for serious allergic symptoms such as swelling or breathing trouble.', questions: 'Ask about drowsiness, other sedating medicines, kidney disease, pregnancy, and age-specific products.' },
  omeprazole: { aliases: [], use: 'Acid reflux and related stomach-acid conditions', safety: 'Take it only as directed. Ask a clinician if symptoms persist, recur, or include difficulty swallowing, vomiting blood, or unexplained weight loss.', sideEffects: 'Headache, stomach upset, or diarrhoea can occur. Seek care for severe or persistent symptoms.', questions: 'Ask how long it should be used, how it fits with other medicines, and whether persistent symptoms need review.' },
  ors: { aliases: ['oral rehydration salts', 'oral rehydration solution'], use: 'Replacing fluids and electrolytes during dehydration', safety: 'Mix and use it exactly as the packet instructs. Do not dilute it incorrectly, and seek urgent help for severe dehydration.', sideEffects: 'Incorrect mixing can be harmful. Seek help for confusion, inability to drink, very little urine, or worsening weakness.', questions: 'Ask about the correct water amount, storage time after mixing, and when a child or adult needs urgent care.' }
};
const interactions = { 'paracetamol|warfarin': { severity: 'Moderate', detail: 'Regular or prolonged use may affect bleeding risk. Confirm the combination with a pharmacist, especially if you use warfarin regularly.' }, 'cetirizine|alcohol': { severity: 'Caution', detail: 'Alcohol may increase drowsiness. Avoid driving and ask a pharmacist about your personal situation.' }, 'omeprazole|clopidogrel': { severity: 'Important', detail: 'This combination may need professional review because acid-reducing medicines can affect clopidogrel activation.' } };

function json(res, status, payload, cookie) {
  const origin = res.req?.headers?.origin; const headers = { 'Content-Type': 'application/json; charset=utf-8', 'Cache-Control': 'no-store', 'X-Content-Type-Options': 'nosniff', 'X-Frame-Options': 'DENY', 'Referrer-Policy': 'same-origin', 'Access-Control-Allow-Credentials': 'true' }; if (allowedOrigins.has(origin)) headers['Access-Control-Allow-Origin'] = origin;
  if (cookie) headers['Set-Cookie'] = cookie;
  res.writeHead(status, headers);
  res.end(JSON.stringify(payload));
}
function error(res, status, code, message) { return json(res, status, { success: false, error: { code, message }, details: { code, message } }); }
function ok(res, data, extra = {}) { return json(res, 200, { success: true, data, ...extra }); }
function bodyOf(req) { return new Promise((resolve, reject) => { let body = ''; req.on('data', chunk => { body += chunk; if (body.length > 100000) reject(Object.assign(new Error('Request too large'), { status: 413 })); }); req.on('end', () => { try { resolve(body ? JSON.parse(body) : {}); } catch { reject(Object.assign(new Error('Invalid JSON'), { status: 400 })); } }); req.on('error', reject); }); }
function sessionFrom(req) { const match = (req.headers.cookie || '').match(/medi_session=([^;]+)/); if (!match) return null; return db.prepare('SELECT u.id,user_id,name,email,language,notifications,expires_at FROM sessions JOIN users u ON u.id=sessions.user_id WHERE token=? AND expires_at > CURRENT_TIMESTAMP').get(match[1]) || null; }
function requireAuth(req, res) { const session = sessionFrom(req); if (!session) { error(res, 401, 'AUTH_REQUIRED', 'Please log in first.'); return null; } return session; }
function limit(req, res) { const key = req.socket.remoteAddress || 'local'; const now = Date.now(); const current = rateWindow.get(key) || { start: now, count: 0 }; if (now - current.start > 60_000) { current.start = now; current.count = 0; } current.count += 1; rateWindow.set(key, current); if (current.count > 120) { error(res, 429, 'RATE_LIMITED', 'Too many requests. Please try again shortly.'); return false; } return true; }
function answerFor(question) {
  const text = String(question).toLowerCase();
  const medicine = Object.keys(medicineFacts).find(name => text.includes(name) || medicineFacts[name].aliases.some(alias => text.includes(alias)));
  if (/(which medicine|what medicine should|prescribe|diagnos)/.test(text)) return { summary: 'I cannot choose a medicine or diagnose a condition. A qualified clinician or pharmacist can assess your situation and discuss appropriate options.', sections: [{ title: 'What I can do', text: 'I can explain a named medicine, general precautions, and questions to take to a healthcare professional.' }] };
  if (/(breath|chest pain|unconscious|seizure|severe bleeding|overdose|facial swelling|serious allergic reaction)/.test(text)) return { summary: 'This may need urgent professional attention. Contact local emergency services now and do not rely on this chat during an emergency.', sections: [{ title: 'Urgent signs', text: 'Severe breathing trouble, chest pain, loss of consciousness, seizure, severe bleeding, overdose, or facial swelling need immediate help.' }] };
  if (!medicine) return { summary: 'I can explain a named medicine, but I need the exact name and your question.', sections: [{ title: 'Please include', text: 'Share the medicine name and what you want to know. For symptoms, include duration and severity.' }, { title: 'Safety', text: 'This is general information, not a diagnosis or personal prescription.' }] };
  const fact = medicineFacts[medicine];
  const sections = [{ title: 'Common use', text: fact.use }, { title: 'Use with care', text: fact.safety }, { title: 'Possible effects', text: fact.sideEffects }, { title: 'Ask a professional', text: fact.questions }, { title: 'Important', text: 'Do not change a dose or treatment without a doctor or pharmacist.' }];
  const focus = /(side effect|reaction|bad|feel)/.test(text) ? fact.sideEffects : /(safe|take|precaution|warning)/.test(text) ? fact.safety : fact.use;
  return { summary: `${medicine[0].toUpperCase()}${medicine.slice(1)}: ${focus}`, sections };
}
function videoFor(name) { const medicine = String(name).trim().toLowerCase(); const use = medicineFacts[medicine]?.use || 'General medicine information should be confirmed with a professional.'; return { medicine: name, scenes: [{ label: '01', title: 'Understand the question', text: `Let us explore ${name} calmly and clearly.`, visual: 'signal' }, { label: '02', title: 'What it is for', text: use + '.', visual: 'relief' }, { label: '03', title: 'Use with care', text: 'Check the label and ask a pharmacist before making personal medicine decisions.', visual: 'care' }], disclaimer: 'General education only. Confirm personal medicine decisions with a doctor or pharmacist.' }; }
function safeMedicine(row) { return { id: row.id, name: row.name, generic: row.generic, className: row.class_name, use: row.use_text, dosageForm: row.dosage_form, strength: row.strength, warnings: row.warnings, adverseEffects: row.adverse_effects, source: row.source, sourceUrl: row.source_url, sourceDate: row.source_date }; }

function createServer() {
  return http.createServer(async (req, res) => {
    try {
      if (!limit(req, res)) return;
      if (req.method === 'OPTIONS') { const origin = req.headers.origin; res.writeHead(204, { ...(allowedOrigins.has(origin) ? { 'Access-Control-Allow-Origin': origin } : {}), 'Access-Control-Allow-Credentials': 'true', 'Access-Control-Allow-Headers': 'Content-Type', 'Access-Control-Allow-Methods': 'GET,POST,PUT,DELETE,OPTIONS' }); return res.end(); }
      const url = new URL(req.url, `http://${req.headers.host || 'localhost'}`);
      if (url.pathname === '/api/health' && req.method === 'GET') return ok(res, { status: 'ok', service: 'medi-dost', timestamp: new Date().toISOString() });
      if (url.pathname === '/api/session' && req.method === 'GET') { const session = sessionFrom(req); return ok(res, { authenticated: Boolean(session), user: session ? { id: session.id, name: session.name, email: session.email } : null }); }
      if (url.pathname === '/api/auth/me' && req.method === 'GET') { const session = sessionFrom(req); if (!session) return json(res, 401, { success: false, authenticated: false, error: { code: 'AUTH_REQUIRED', message: 'Please log in first.' } }); return json(res, 200, { success: true, authenticated: true, user: { id: session.id, name: session.name, email: session.email } }); }
      if (url.pathname === '/api/signup' && req.method === 'POST') { const input = await bodyOf(req); if (!input.email || !input.password || String(input.password).length < 8) return error(res, 400, 'INVALID_INPUT', 'Email and a password of at least 8 characters are required.'); try { const result = db.prepare('INSERT INTO users (name,email,password_hash) VALUES (?,?,?)').run(String(input.name || 'Medi Dost user').trim().slice(0, 80), String(input.email).trim().toLowerCase(), hashPassword(String(input.password))); return ok(res, { id: Number(result.lastInsertRowid), email: String(input.email).trim().toLowerCase() }); } catch { return error(res, 409, 'EMAIL_EXISTS', 'An account with that email already exists.'); } }
      if ((url.pathname === '/api/login' || url.pathname === '/api/auth/login') && req.method !== 'POST') return error(res, 405, 'METHOD_NOT_ALLOWED', 'Use POST to log in.');
      if ((url.pathname === '/api/login' || url.pathname === '/api/auth/login') && req.method === 'POST') { const input = await bodyOf(req); if (!input.email || !input.password) return error(res, 400, 'INVALID_INPUT', 'Email and password are required.'); const user = db.prepare('SELECT * FROM users WHERE email=?').get(String(input.email).trim().toLowerCase()); if (!user || !verifyPassword(String(input.password), user.password_hash)) return error(res, 401, 'INVALID_CREDENTIALS', 'Invalid email or password.'); const token = crypto.randomBytes(32).toString('hex'); db.prepare("INSERT INTO sessions (token,user_id,expires_at) VALUES (?,?,datetime('now','+7 days'))").run(token, user.id); return json(res, 200, { success: true, message: 'Login successful', authenticated: true, user: { id: user.id, name: user.name, email: user.email } }, `medi_session=${token}; HttpOnly; SameSite=Lax; Path=/; Max-Age=604800`); }
      if (url.pathname === '/api/logout' && req.method === 'POST') { const match = (req.headers.cookie || '').match(/medi_session=([^;]+)/); if (match) db.prepare('DELETE FROM sessions WHERE token=?').run(match[1]); return json(res, 200, { success: true, authenticated: false }, 'medi_session=; HttpOnly; SameSite=Lax; Path=/; Max-Age=0'); }
      if (url.pathname === '/api/search' && req.method === 'GET') { const query = String(url.searchParams.get('q') || '').trim(); if (query.length < 2) return ok(res, { medicines: [], articles: [], tools: [] }); const like = `%${query}%`; const rows = db.prepare('SELECT * FROM medicines WHERE name LIKE ? OR generic LIKE ? OR class_name LIKE ? ORDER BY name LIMIT 20').all(like, like, like); return ok(res, { medicines: rows.map(safeMedicine), articles: [], tools: [] }); }
      const medicineMatch = url.pathname.match(/^\/api\/medicines\/(\d+)$/); if (medicineMatch && req.method === 'GET') { const row = db.prepare('SELECT * FROM medicines WHERE id=?').get(Number(medicineMatch[1])); if (!row) return error(res, 404, 'NOT_FOUND', 'Medicine not found.'); return ok(res, safeMedicine(row)); }
      if (url.pathname === '/api/medicines' && req.method === 'GET') { const query = String(url.searchParams.get('q') || '').trim(); const page = Math.max(1, Number(url.searchParams.get('page') || 1)); const rows = query ? db.prepare('SELECT * FROM medicines WHERE name LIKE ? OR generic LIKE ? OR class_name LIKE ? ORDER BY name LIMIT 20 OFFSET ?').all(`%${query}%`,`%${query}%`,`%${query}%`,(page-1)*20) : db.prepare('SELECT * FROM medicines ORDER BY name LIMIT 20 OFFSET ?').all((page-1)*20); return ok(res, { items: rows.map(safeMedicine), page, pageSize: 20 }); }
      if (url.pathname === '/api/ai/chat' || url.pathname === '/api/chat') { if (req.method !== 'POST') return error(res, 405, 'METHOD_NOT_ALLOWED', 'Use POST for chat.'); const session = requireAuth(req, res); if (!session) return; const input = await bodyOf(req); if (!input.message && !input.question) return error(res, 400, 'INVALID_INPUT', 'A message is required.'); const message = String(input.message || input.question).trim(); const conversationId = String(input.conversationId || crypto.randomUUID()); db.prepare('INSERT OR IGNORE INTO conversations (id,user_id) VALUES (?,?)').run(conversationId, session.id); db.prepare('INSERT INTO messages (conversation_id,role,content) VALUES (?,?,?)').run(conversationId, 'user', message); const answer = answerFor(message); db.prepare('INSERT INTO messages (conversation_id,role,content) VALUES (?,?,?)').run(conversationId, 'assistant', answer.summary); return ok(res, { answer: answer.summary, sources: [], safetyNotice: 'General health information only. This is not a diagnosis or prescription.', conversationId, sections: answer.sections }, { answer: { summary: answer.summary, sections: answer.sections }, question: message }); }
      if (url.pathname === '/api/medicine-video' && req.method === 'POST') { const input = await bodyOf(req); if (!input.medicine) return error(res, 400, 'INVALID_INPUT', 'Choose a medicine first.'); const story = videoFor(input.medicine); return ok(res, story, story); }
      if (url.pathname === '/api/interactions' || url.pathname === '/api/interactions/check') { if (req.method !== 'POST') return error(res, 405, 'METHOD_NOT_ALLOWED', 'Use POST for interactions.'); if (!requireAuth(req, res)) return; const input = await bodyOf(req); if (!Array.isArray(input.medicines) || input.medicines.length < 2) return error(res, 400, 'INVALID_INPUT', 'Add at least two medicines.'); const names = input.medicines.map(item => String(item).toLowerCase().trim()); const match = Object.entries(interactions).find(([key]) => key.split('|').every(part => names.includes(part))); const result = match ? { status: 'known', severity: match[1].severity, detail: match[1].detail } : { status: 'unknown', message: 'Interaction information could not be verified from the selected local reference set.' }; return ok(res, { medicines: input.medicines, result }, { medicines: input.medicines, result }); }
      if (url.pathname === '/api/reminders' && req.method === 'GET') { const session = requireAuth(req, res); if (!session) return; return ok(res, db.prepare('SELECT * FROM reminders WHERE user_id=? ORDER BY scheduled_at').all(session.id)); }
      if (url.pathname === '/api/reminders' && req.method === 'POST') { const session = requireAuth(req, res); if (!session) return; const input = await bodyOf(req); if (!input.medicineName || !input.scheduledAt) return error(res, 400, 'INVALID_INPUT', 'Medicine name and scheduled time are required.'); const result = db.prepare('INSERT INTO reminders (user_id,medicine_name,note,scheduled_at,enabled) VALUES (?,?,?,?,?)').run(session.id, String(input.medicineName).trim(), String(input.note || '').trim(), String(input.scheduledAt), input.enabled === false ? 0 : 1); return ok(res, db.prepare('SELECT * FROM reminders WHERE id=?').get(Number(result.lastInsertRowid))); }
      const reminderMatch = url.pathname.match(/^\/api\/reminders\/(\d+)$/); if (reminderMatch) { const session = requireAuth(req, res); if (!session) return; const id = Number(reminderMatch[1]); if (req.method === 'DELETE') { db.prepare('DELETE FROM reminders WHERE id=? AND user_id=?').run(id, session.id); return ok(res, { id }); } if (req.method === 'PUT') { const input = await bodyOf(req); db.prepare('UPDATE reminders SET medicine_name=?,note=?,scheduled_at=?,enabled=?,updated_at=CURRENT_TIMESTAMP WHERE id=? AND user_id=?').run(String(input.medicineName || '').trim(), String(input.note || '').trim(), String(input.scheduledAt || ''), input.enabled === false ? 0 : 1, id, session.id); return ok(res, db.prepare('SELECT * FROM reminders WHERE id=? AND user_id=?').get(id, session.id)); } }
      if (url.pathname === '/api/saved-medicines' && req.method === 'GET') { const session = requireAuth(req, res); if (!session) return; return ok(res, db.prepare('SELECT m.* FROM medicines m JOIN saved_medicines s ON s.medicine_id=m.id WHERE s.user_id=? ORDER BY s.created_at DESC').all(session.id).map(safeMedicine)); }
      if (url.pathname === '/api/saved-medicines' && req.method === 'POST') { const session = requireAuth(req, res); if (!session) return; const input = await bodyOf(req); const medicine = db.prepare('SELECT id FROM medicines WHERE id=? OR name=?').get(Number(input.medicineId || 0), String(input.name || '')); if (!medicine) return error(res, 404, 'NOT_FOUND', 'Medicine not found.'); db.prepare('INSERT OR IGNORE INTO saved_medicines (user_id,medicine_id) VALUES (?,?)').run(session.id, medicine.id); return ok(res, { medicineId: medicine.id }); }
      const savedMatch = url.pathname.match(/^\/api\/saved-medicines\/(\d+)$/); if (savedMatch && req.method === 'DELETE') { const session = requireAuth(req, res); if (!session) return; db.prepare('DELETE FROM saved_medicines WHERE user_id=? AND medicine_id=?').run(session.id, Number(savedMatch[1])); return ok(res, { medicineId: Number(savedMatch[1]) }); }
      if (url.pathname === '/api/profile' && req.method === 'GET') { const session = requireAuth(req, res); if (!session) return; return ok(res, session); }
      if (req.method === 'GET') { const requested = decodeURIComponent(url.pathname === '/' ? '/index.html' : url.pathname); const filePath = path.resolve(ROOT, `.${requested}`); if (filePath.startsWith(path.resolve(ROOT) + path.sep) && fs.existsSync(filePath) && fs.statSync(filePath).isFile()) { const types = { '.html': 'text/html; charset=utf-8', '.js': 'text/javascript; charset=utf-8', '.css': 'text/css; charset=utf-8', '.md': 'text/plain; charset=utf-8' }; res.writeHead(200, { 'Content-Type': types[path.extname(filePath)] || 'application/octet-stream', 'X-Content-Type-Options': 'nosniff' }); return fs.createReadStream(filePath).pipe(res); } }
      return error(res, 404, 'NOT_FOUND', 'Not found.');
    } catch (err) { console.error(err); return error(res, err.status || 500, err.status ? 'REQUEST_ERROR' : 'INTERNAL_ERROR', err.status ? err.message : 'The server could not process that request.'); }
  });
}

if (require.main === module) {
  const server = createServer();
  server.on('error', (err) => {
    if (err.code === 'EADDRINUSE') {
      console.error(`Medi Dost could not start: port ${PORT} is already in use. Stop the existing Medi Dost server or set PORT to another value.`);
    } else {
      console.error(`Medi Dost could not start: ${err.message}`);
    }
    process.exitCode = 1;
  });
  server.listen(PORT, '0.0.0.0', () => console.log(`Medi Dost server running at http://localhost:${PORT}`));
}
module.exports = { createServer, db };
